apiVersion: v1
kind: Service
metadata:
  name: distribution-hosted
  namespace: mirror-distribution
  labels:
    app: distribution-hosted
spec:
  type: NodePort
  selector:
    app: distribution-hosted
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 30051
      protocol: TCP
